/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void custom_slider1_change1(GCustomSlider source, GEvent event) { //_CODE_:outsideTempSlider:603799:
  outsideTemp = outsideTempSlider.getValueF();
  
} //_CODE_:outsideTempSlider:603799:

public void custom_slider2_change1(GCustomSlider source, GEvent event) { //_CODE_:houseTempSlider:939036:
  setHouseTemp = houseTempSlider.getValueF();
} //_CODE_:houseTempSlider:939036:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  outsideTempSlider = new GCustomSlider(this, 450, 500, 250, 50, "blue18px");
  outsideTempSlider.setShowValue(true);
  outsideTempSlider.setShowLimits(true);
  outsideTempSlider.setLimits(20.0, -20.0, 40.0);
  outsideTempSlider.setShowTicks(true);
  outsideTempSlider.setNumberFormat(G4P.DECIMAL, 2);
  outsideTempSlider.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  outsideTempSlider.setOpaque(true);
  outsideTempSlider.addEventHandler(this, "custom_slider1_change1");
  houseTempSlider = new GCustomSlider(this, 100, 500, 250, 50, "purple18px");
  houseTempSlider.setShowValue(true);
  houseTempSlider.setShowLimits(true);
  houseTempSlider.setLimits(23.0, 15.0, 30.0);
  houseTempSlider.setShowTicks(true);
  houseTempSlider.setNumberFormat(G4P.DECIMAL, 2);
  houseTempSlider.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  houseTempSlider.setOpaque(true);
  houseTempSlider.addEventHandler(this, "custom_slider2_change1");
}

// Variable declarations 
// autogenerated do not edit
GCustomSlider outsideTempSlider; 
GCustomSlider houseTempSlider; 
